### ISSUE TITLE
ERROR [launcher]: Cannot start Edge Headless 

### ISSUE THREAD

**Issue by toonnyyyy** [ChiragRupani/karma-chromiumedge-launcher#10]
In our environment we have a Jenkins server that runs the Jasmine unit tests with the karma-chromiumedge-launcher plugin. But with Edge versions higher than v95.x we get the this error ( ERROR [launcher]: Cannot start Edge Headless ) and we are unable to run the unit tests

System info:

OS: Microsoft Windows Server 2012 R2 Datacenter
Edge version failing: 96.x +
Edge version working: < 95.x

Full log:

E:\Jenkins\workspace\e_digidoc-dwc-multibranch_master>npm run test-coverage 

> digidoc-web@0.0.1 test-coverage E:\Jenkins\workspace\e_digidoc-dwc-multibranch_master
> ng test --browsers=EdgeHeadless --watch=false --code-coverage

- Generating browser application bundles (phase: setup)...
Compiling @angular/core/testing : es2015 as esm2015
Compiling @angular/platform-browser/testing : es2015 as esm2015
Compiling @angular/compiler/testing : es2015 as esm2015
Compiling @angular/common/testing : es2015 as esm2015
Compiling @angular/common/http/testing : es2015 as esm2015
Compiling @angular/router/testing : es2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : es2015 as esm2015
07 01 2022 10:06:14.931:INFO [karma-server]: Karma v6.3.6 server started at http://localhost:9876/
07 01 2022 10:06:14.935:INFO [launcher]: Launching browsers EdgeHeadless with concurrency unlimited
07 01 2022 10:06:14.939:INFO [launcher]: Starting browser Edge Headless
07 01 2022 10:06:14.998:ERROR [launcher]: Cannot start Edge Headless
	
07 01 2022 10:06:14.999:ERROR [launcher]: Edge Headless stdout: 
07 01 2022 10:06:14.999:ERROR [launcher]: Edge Headless stderr: 
07 01 2022 10:06:15.003:INFO [launcher]: Trying to start Edge Headless again (1/2).
07 01 2022 10:06:15.577:ERROR [launcher]: Cannot start Edge Headless
	
07 01 2022 10:06:15.578:ERROR [launcher]: Edge Headless stdout: 
07 01 2022 10:06:15.578:ERROR [launcher]: Edge Headless stderr: 
07 01 2022 10:06:15.583:INFO [launcher]: Trying to start Edge Headless again (2/2).
07 01 2022 10:06:15.616:ERROR [launcher]: Cannot start Edge Headless
	
07 01 2022 10:06:15.616:ERROR [launcher]: Edge Headless stdout: 
07 01 2022 10:06:15.616:ERROR [launcher]: Edge Headless stderr: 
07 01 2022 10:06:15.627:ERROR [launcher]: Edge Headless failed 2 times (cannot start). Giving up.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! digidoc-web@0.0.1 test-coverage: `ng test --browsers=EdgeHeadless --watch=false --code-coverage`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the digidoc-web@0.0.1 test-coverage script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\windows\system32\config\systemprofile\AppData\Roaming\npm-cache\_logs\2022-01-07T09_06_15_797Z-debug.log

**Comment by ChiragRupani** [comment]
Thanks for sharing all the required details. One thing, I observed that Edge browser is not available to download on the Window Server 2012 - https://www.microsoft.com/en-us/edge#evergreen
![image](https://user-images.githubusercontent.com/36813124/148952739-57858c12-cd6c-4922-a477-6c4c68ea6ca1.png)

May be Windows Server 2012 is no longer supported. 

Alternatively, if you know path of Edge installation location on the server - checking below path using `dir` command to ensure Edge.exe is present at the path and then try adding below/correct path of Edge in karma.conf.js:

```bash
# Add at top of karma.conf.js
process.env.EDGE_BIN =
  "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe";
```

**Comment by olivier-van-wijngaarden** [comment]
Hi,
process.env.EDGE_BIN = "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe";
is already set, and the path to Edge.exe is verified. I'm afraid this had not the desired effect.

**Comment by ChiragRupani** [comment]
Since this library just provides path of Edge Browser to Karma, I am afraid I can do much to fix the issue you are the facing.
