### ISSUE TITLE
Cannot load browser "EdgeHeadless": it is not registered!

### ISSUE THREAD

**Issue by OZZlE** [ChiragRupani/karma-chromiumedge-launcher#20]
ng test --no-watch --no-progress --browsers=EdgeHeadless --code-coverage
        17 04 2024 13:44:58.442:INFO [karma-server]: Karma v6.4.2 server started at http://localhost:9876/
        17 04 2024 13:44:58.449:INFO [launcher]: Launching browsers EdgeHeadless with concurrency unlimited
        17 04 2024 13:44:58.450:ERROR [launcher]: Cannot load browser "EdgeHeadless": it is not registered! Perhaps you are missing some plugin?
        17 04 2024 13:44:58.451:ERROR [karma-server]: Error: Found 1 load error
            at Server.<anonymous> (C:\..censored...\node_modules\karma\lib\server.js:243:26)
            at Object.onceWrapper (node:events:632:28)
            at Server.emit (node:events:530:35)
            at Server.emit (node:domain:488:12)
            at emitListeningNT (node:net:1906:10)
            at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

karma.conf.js

    // Karma configuration file, see link for more information
    // https://karma-runner.github.io/1.0/config/configuration-file.html

    process.env.CHROME_BIN = require('puppeteer').executablePath()

    module.exports = function (config) {
      config.set({
        basePath: "",
        frameworks: ["jasmine", "@angular-devkit/build-angular"],
        plugins: [
          require("karma-jasmine"),
          // require("karma-chrome-launcher"),
          require("karma-jasmine-html-reporter"),
          //      require("karma-coverage-istanbul-reporter"),
          require("@angular-devkit/build-angular/plugins/karma"),
          require('@chiragrupani/karma-chromium-edge-launcher'),
        ],
        client: {
          jasmine: {
            // you can add configuration options for Jasmine here
            // the possible options are listed at https://jasmine.github.io/api/edge/Configuration.html
            // for example, you can disable the random execution with `random: false`
            // or set a specific seed with `seed: 4321`
          },
          clearContext: false, // leave Jasmine Spec Runner output visible in browser
        },
        jasmineHtmlReporter: {
          suppressAll: true, // removes the duplicated traces
        },
        coverageReporter: {
          dir: require("path").join(__dirname, "./coverage/censored"),
          subdir: ".",
          reporters: [
            { type: 'lcov' },
            { type: "html" },
            { type: "text-summary" }
          ],
        },
        reporters: ["progress", "kjhtml"],
        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: true,
        browsers: ['Edge', 'EdgeAnyHeadless'],
        customLaunchers: {
          EdgeHeadlessCI: {
            base: "EdgeAnyHeadless",
            flags: ["--no-sandbox"],
          },
        },
        singleRun: false,
        restartOnFileChange: true,
      });
    };

package.json (relevant parts)

    {
      "name": "censored",
      "private": true,
      "dependencies": {
        "@angular/animations": "^17.0.0",
        "@angular/cdk": "^17.0.0",
        "@angular/common": "^17.0.0",
        "@angular/compiler": "^17.0.0",
        "@angular/core": "^17.0.0",
        "@angular/forms": "^17.0.0",
        "@angular/localize": "^17.0.0",
        "@angular/material": "^17.0.0",
        "@angular/platform-browser": "^17.0.0",
        "@angular/platform-browser-dynamic": "^17.0.0",
        "@angular/router": "^17.0.0",
        "@coreui/angular": "^4.7.0",
        "@fortawesome/angular-fontawesome": "^0.10.2",

        "ngx-toastr": "^16.0.0",
        "puppeteer": "^22.6.5",
        "rxjs": "^7.0.0",
        "tslib": "^2.3.0",
        "typescript": "^5.4.5",
        "zone.js": "~0.14.0"
      },
      "devDependencies": {
        "@angular-builders/custom-webpack": "^17.0.0",
        "@angular-devkit/build-angular": "^17.0.0",
        "@angular/cli": "^17.0.0",
        "@angular/compiler-cli": "^17.0.0",
        "@chiragrupani/karma-chromium-edge-launcher": "^2.3.1",
        "@types/jasmine": "~5.1.4",
        "@types/jest": "^29.5.12",
        "@types/node": "^12.20.42",
        "@types/pdfmake": "^0.2.9",
        "assets-webpack-plugin": "^7.1.1",
        "jasmine-core": "~5.1.2",
        "karma": "^6.4.2",
        "karma-chrome-launcher": "~3.2.0",
        "karma-coverage": "~2.2.1",
        "karma-edgium-launcher": "^4.0.0-0",
        "karma-jasmine": "~5.1.0",
        "karma-jasmine-html-reporter": "~2.1.0",
        "prettier": "^3.2.5",
        "webpack": "^5.68.0"
      }
    }

I run `ng test --no-watch --no-progress --browsers=EdgeHeadless --code-coverage`  on a windows 11 PC that has Edge

I intend to run it in Github Action on Windows 2019 runner where I dont know path to Edge also...

**Comment by OZZlE** [comment]
the documentation here seems to mix "EdgeHeadless" and "EdgeHeadlessCI" everywhere so can't really follow

**Comment by OZZlE** [comment]
ng test --no-watch --no-progress --browsers=EdgeHeadlessCI --code-coverage
17 04 2024 14:03:37.326:INFO [karma-server]: Karma v6.4.2 server started at http://localhost:9876/
17 04 2024 14:03:37.329:INFO [launcher]: Launching browsers EdgeHeadlessCI with concurrency unlimited
17 04 2024 14:03:37.330:ERROR [launcher]: Cannot load browser "EdgeHeadlessCI": it is not registered! Perhaps you are missing some plugin?

**Comment by OZZlE** [comment]
tried also

process.env.CHROME_BIN = require('puppeteer').executablePath()
process.env.EDGE_ANY_BIN = "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"
process.env.EDGE_ANY_HEADLESS_BIN = "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"
process.env.EDGE_ANY_HEADLESS_CI_BIN = "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"

**Comment by ChiragRupani** [comment]
Could you update LogLevel in `karma.conf.js` to debug as below:
`logLevel: config.LOG_DEBUG`

Also, `browsers: ['EdgeAnyHeadless']` is sufficient, there is no need of custom launcher in your case, since it is Windows. so remove it. Is it working on your local PC and no working on GitHub Action, then in that case, Edge Browser might not be installed by default where GitHub Action is running, you may need to add step to download / install the browser

**Comment by OZZlE** [comment]
ng test --no-watch --no-progress --browsers=EdgeAnyHeadless --code-coverage
19 04 2024 12:04:49.265:INFO [karma-server]: Karma v6.4.2 server started at http://localhost:9876/
19 04 2024 12:04:49.267:INFO [launcher]: Launching browsers EdgeAnyHeadless with concurrency unlimited
19 04 2024 12:04:49.269:ERROR [launcher]: Cannot load browser "EdgeAnyHeadless": it is not registered! Perhaps you are missing some plugin?
19 04 2024 12:04:49.269:ERROR [karma-server]: Error: Found 1 load error
    at Server.<anonymous> (C:\..censored...\node_modules\karma\lib\server.js:243:26)
    at Object.onceWrapper (node:events:632:28)
    at Server.emit (node:events:530:35)
    at Server.emit (node:domain:488:12)
    at emitListeningNT (node:net:1906:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

**Comment by ChiragRupani** [comment]
Is this log from local Windows 11 machine or GH Action?
Also, if you've karma installed globally, please uninstall it - `npm uninstall -g karma`
and update plugins Array in `karma.conf.js` as below:
```
 plugins: [
      require("karma-jasmine"),
      require("@chiragrupani/karma-chromium-edge-launcher"),
      require("karma-jasmine-html-reporter"),
      require("karma-coverage-istanbul-reporter"),
      "@angular-devkit/build-angular/plugins/karma",
    ],
```

**Comment by OZZlE** [comment]
I get the same log locally and inside github actions, I have Edge installed locally. I didn't have karma globally installed

I updated those packages and trid again now with those plugins in that order you wrote, I get the same error anyway

**Comment by OZZlE** [comment]
I went with installing chrome on linux (debian) in the github action instead which worked

      - name: Install Chrome
        run: |
          wget https://repo7.sebank.se/artifactory/google.dl/linux/direct/google-chrome-stable_current_amd64.deb
          apt-get update
          apt-get --yes install ./google-chrome-stable_current_amd64.deb

**Comment by ChiragRupani** [comment]
It is working fine for me using GitHub Action on both Ubuntu OS and Windows OS.

Sample workflow:
```yml
name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash
        working-directory: ./app

    strategy:
      matrix:
        node-version: [22.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
```

I am afraid if I can check further.
