### ISSUE TITLE
Can't get Edge Headless to run under Linux

### ISSUE THREAD

**Issue by Speedy0197** [ChiragRupani/karma-chromiumedge-launcher#7]
Hi,

i am not sure if this is an actual issue or maybe i am doing something wrong.

I want to run our Karma Unittests in a docker container with headless Edge.
Karma launcher appareantly starts the Browser and connects on socket ... with id ...
But nothing happens, after the timeout headless Chrome just gets killed.

I really appreciate any help you can provide.

Speedy0197

**Comment by ChiragRupani** [comment]
Could you please provide more information:
1. What is npm test command/ what browser channel you are using e.g. `ng test "--no-watch" "--browsers=EdgeDevHeadless"`
2. Check if Edge is installed at `/usr/bin/microsoft-edge-dev` , else you need to set in environment variable `process.env.EDGE_DEV_BIN`
3. What exactly is logged by Karma like below


```
10 11 2020 03:27:17.548:INFO [karma-server]: Karma v5.2.3 server started at http://localhost:9876/
10 11 2020 03:27:17.551:INFO [launcher]: Launching browsers EdgeDevHeadless with concurrency unlimited
10 11 2020 03:27:17.555:INFO [launcher]: Starting browser Edge Dev Headless
10 11 2020 03:27:22.629:INFO [Edge 88.0.673.0 (Linux x86_64)]: Connected on socket fyvLqOXHzRiLSfV0AAAA with id 32932866
Edge 88.0.673.0 (Linux x86_64): Executed 0 of 1 SUCCESS (0 secs / 0 secs)
Edge 88.0.673.0 (Linux x86_64): Executed 1 of 1 SUCCESS (0 secs / 0.06 secs)
```

**Comment by Speedy0197** [comment]
Hi,

we are using Gitlab CI, but i believe its easier to show you with docker.
Here is a our dockerfile. You can see how edge gets installed.
in /usr/bin/ there is microsoft-edge and microsoft-edge-dev

```
FROM trion/ng-cli-karma:9.1.1
COPY . /app
WORKDIR /app/licensemanager/frontend
RUN npm install
RUN apt update && apt install -y gpg apt-transport-https
RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
RUN install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
RUN sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
RUN apt update && apt install -y microsoft-edge-dev
```

Afterwards i ran npm run test:edge
`"test:edge": "ng test --codeCoverage=true --browsers=EdgeHeadlessCI",`

 i have tried lots of different settings here, like EdgeHeadless
custom launcher:
`EdgeHeadlessCI: {
        base: "Edge",
        flags: [
          // "--user-data-dir=''", 
          "--no-sandbox",
          "--headless",
          "--disable-gpu",
        ],
      },`


Which produces this:
```
13 11 2020 13:10:21.748:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
13 11 2020 13:10:21.763:INFO [launcher]: Launching browsers EdgeHeadlessCI with concurrency 1
13 11 2020 13:10:21.771:INFO [launcher]: Starting browser Edge
13 11 2020 13:11:43.341:ERROR [launcher]: Cannot start Edge
        Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
[1113/131024.014126:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

13 11 2020 13:11:43.345:ERROR [launcher]: Edge stdout:
```

so i start dbus with 
`/etc/init.d/dbus start`
which removes the error message with the bus but edge still doesnt get started

**Comment by ChiragRupani** [comment]
Not sure If I can help here, since issue is socket is not established for Karma to launch browser. One thing can be checked if edge browser is installed properly using below cmd script:

```
echo "var which = require('which'); function GetLinuxBin(command) { try { let result = which.sync(command); console.log('Exec Access OK: ' + result); } catch (e) { console.log('Access Not Ok'); };}; GetLinuxBin('microsoft-edge'); console.log(process.platform);" > app.js

node app.js
```

**Comment by Speedy0197** [comment]
i tried your script: 
Exec Access OK: /usr/bin/microsoft-edge
linux
Any Ideas or suggestions?

**Comment by ChiragRupani** [comment]
The above log suggests that it is not issue with Karma-Chromiumedge-launcher since the similar code is used in this package and the path is sent to Karma to launch.  Also, edge browser is installed fine. Even if you tested with other browsers/launcher you will get same error.

Now, since socket is not established it is something wrong with Karma. You need to debug that. One way is I assume there is `Karma.conf.js` for specifying Karma config. In that file, change Log Level as ` logLevel: config.LOG_DEBUG,`. It will give detailed output of each plugin loaded by Karma and will definitely help in finding issue.

**Comment by Speedy0197** [comment]
Hi,

i have tried a few more things:
setting the Karma Log Level to Debug already helped me to understand the problem.
The launcher starts Edge (i think this actually works fine), but edge then crashes.
So i downloaded an ubuntu image (VMWare) and tried to run the tests with edge (normal, not headless mode).
Edge gets opened and you can see the status: karma 5.2.3 connected
After a few a seconds the browser switches to site not available.

So i am still not sure if its edge that actually crashes or if karma has a problem.

Do you have a working linux example repo/test by any chance?

Thanks for your help, highly appreciated.

**Comment by ChiragRupani** [comment]
I have verified on Ubuntu OS with Edge Headless for this [Angular App](https://github.com/ChiragRupani/Ngrx8StoreSample).

Command on machine with Edge already installed:
git clone 'https://github.com/ChiragRupani/Ngrx8StoreSample'
cd Ngrx8StoreSample
cd todoapp
npm test -- --no-watch --browsers=EdgeHeadless

**Comment by anthony-redFox** [comment]
@Speedy0197  just add flags
'--no-sandbox'
'--disable-gpu',
'--disable-dev-shm-usage'

disable-dev-shm-usage - special for linux docker containers, for me is works, this is flag found in chrome launcher

cc @ChiragRupani  I think it is make sense to add to standard implementation

**Comment by ChiragRupani** [comment]
This issue has been marked as close because it has not had recent activity. Thank you for your contributions.
